### ISSUE TITLE
Realese Note and Doc

### ISSUE THREAD

**Issue by Le-Syl21** [NoobieDog/JD101#1]
Hi,

Why a custom firmware ?

What can he do ?

How to install it ?

Can you edit your README.md to answer thats  questions ?

**Comment by NoobieDog** [comment]
Not really, but you can read all about why and what i did here:

https://noobiedog.com/obd2-reader-redesigned-part-4-putting-it-all-together/

**Comment by Le-Syl21** [comment]
Thx
